[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
vela_anchor = "FW6P7G9yPBqGAGsZ6Aa7upC9whF69QMH4ZJaBJjFsLVK"

[programs.devnet]
vela_anchor = "FW6P7G9yPBqGAGsZ6Aa7upC9whF69QMH4ZJaBJjFsLVK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "ANCHOR_PROVIDER_URL=http://127.0.0.1:8899 ANCHOR_WALLET=~/.config/solana/id.json yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""


[test]
startup_wait = 20000

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tools/.bin/token_metadata.so"