use anchor_lang::prelude::*;

// This file is auto-generated by scripts/parse-events.ts
// Generated at: 2026-01-27T08:58:37.101Z

/// Stake created event
/// Triggered at the end of successful handler_create_stake execution
#[event]
pub struct StakeCreatedEvent {
    /// User wallet address
    pub user: Pubkey,
    /// User's referral ID
    pub referral_id: u32,
    /// Order slot index in user account (0-14)
    pub order_index: u8,
    /// Staked amount (smallest unit)
    pub amount: u64,
    /// Staking period type (1=7 days, 2=30 days, 3=90 days)
    pub period_type: u8,
    /// Daily rate snapshot at creation (basis points, 10000=100%)
    pub initial_daily_rate: u64,
    /// Staking start timestamp
    pub start_time: i64,
    /// Staking expiry timestamp
    pub end_time: i64,
    /// Global total staked (after update)
    pub global_total_staked: u64,
    /// Daily deposited total (after this deposit)
    pub daily_deposited: u64,
    /// Daily deposit cap
    pub daily_deposit_cap: u64,
    /// Per-address staking cap applied to this transaction
    pub user_stake_cap: u64,
}

/// Unstake event
/// Triggered at the end of successful handler_unstake execution
#[event]
pub struct UnstakedEvent {
    /// User wallet address
    pub user: Pubkey,
    /// User's referral ID
    pub referral_id: u32,
    /// Unstaked order slot index (0-14)
    pub order_index: u8,
    /// Returned principal
    pub principal: u64,
    /// Base interest (excluding NFT boost, before tax)
    pub base_interest: u64,
    /// NFT boost interest
    pub boost_interest: u64,
    /// Total interest (base + boost, before tax)
    pub total_interest: u64,
    /// Tax amount (burned to dead address)
    pub tax_amount: u64,
    /// Net interest received by user (after tax)
    pub interest_to_user: u64,
    /// Total amount received by user (principal + net interest)
    pub total_to_user: u64,
    /// NFT boost ratio (basis points, 0=no NFT)
    pub nft_boost_bps: u64,
    /// NFT Mint bound to user (Pubkey::default() if none)
    pub nft_mint: Pubkey,
    /// Global total staked (after update)
    pub global_total_staked: u64,
    /// Global cumulative interest paid (after update)
    pub global_total_interest_paid: u64,
    /// Operation timestamp
    pub timestamp: i64,
}

/// Claim interest event
/// Triggered at the end of successful handler_claim_interest execution
#[event]
pub struct InterestClaimedEvent {
    /// User wallet address
    pub user: Pubkey,
    /// Claimed order slot index (0-14)
    pub order_index: u8,
    /// Base interest (excluding NFT boost, before tax)
    pub base_interest: u64,
    /// NFT boost interest
    pub boost_interest: u64,
    /// Total interest (base + boost, before tax)
    pub total_interest: u64,
    /// Tax amount (burned to dead address)
    pub tax_amount: u64,
    /// Net interest received by user (after tax)
    pub user_receive: u64,
    /// NFT boost ratio (basis points, 0=no NFT)
    pub nft_boost_bps: u64,
    /// NFT Mint bound to user (Pubkey::default() if none)
    pub nft_mint: Pubkey,
    /// Global cumulative interest paid (after update)
    pub global_total_interest_paid: u64,
    /// Operation timestamp
    pub timestamp: i64,
}

/// Referral binding event
/// Triggered when user successfully binds a referrer
#[event]
pub struct ReferralBindingEvent {
    /// Parent's Solana address
    pub parent_wallet: Pubkey,
    /// Parent's referrer ID
    pub parent_id: u32,
    /// My Solana address
    pub my_wallet: Pubkey,
    /// My referrer ID
    pub my_id: u32,
    /// Binding timestamp
    pub timestamp: i64,
}

/// Claim community reward event
/// Triggered at the end of successful handler_claim_community_profit execution
#[event]
pub struct CommunityProfitClaimedEvent {
    /// User wallet address
    pub user: Pubkey,
    /// User's referral ID
    pub referral_id: u32,
    /// Direct reward amount claimed
    pub direct_reward_amount: u64,
    /// Team reward amount claimed
    pub team_reward_amount: u64,
    /// Total claimed amount
    pub total_amount: u64,
    /// Operation timestamp
    pub timestamp: i64,
}

/// Token locked event
/// Triggered when tokens are locked into the vault
#[event]
pub struct TokensLockedEvent {
    /// User wallet address
    pub user: Pubkey,
    /// Locked amount
    pub amount: u64,
    /// Total locked amount after this operation
    pub total_locked: u64,
    /// Lock timestamp
    pub timestamp: i64,
}

/// Node reward pool weekly refresh event
#[event]
pub struct NodePoolRefreshed {
    /// New week number
    pub week_number: u64,
    /// Number of weeks skipped since last refresh
    pub weeks_skipped: u64,
    /// Diamond pool unclaimed amount returned to root
    pub diamond_unclaimed_to_root: u64,
    /// Gold pool unclaimed amount returned to root
    pub gold_unclaimed_to_root: u64,
    /// New diamond pool amount (last week -> claimable)
    pub diamond_new_pool: u64,
    /// New gold pool amount (last week -> claimable)
    pub gold_new_pool: u64,
}

/// Node reward pool claim event
#[event]
pub struct NodePoolRewardClaimed {
    /// User wallet address
    pub user: Pubkey,
    /// Node type (1=Diamond, 2=Gold)
    pub node_type: u8,
    /// Week number of the claimed reward
    pub week_number: u64,
    /// Claimed amount
    pub amount: u64,
}

/// Diamond NFT verification event
#[event]
pub struct DiamondVerificationEvent {
    pub user: Pubkey,
    pub nft_mint: Pubkey,
    pub collection_mint: Pubkey,
    pub owns_nft: bool,
    pub balance: u64,
}

/// Gold NFT verification event
#[event]
pub struct GoldVerificationEvent {
    pub user: Pubkey,
    pub nft_mint: Pubkey,
    pub collection_mint: Pubkey,
    pub owns_nft: bool,
    pub balance: u64,
}

/// Token claim event
#[event]
pub struct TokensClaimedEvent {
    pub user: Pubkey,
    pub nft_mint: Pubkey,
    pub amount: u64,
    pub total_released: u64,
    pub timestamp: i64,
}

/// Airdrop fund deposit event
#[event]
pub struct AirdropFundDepositedEvent {
    pub depositor: Pubkey,
    pub amount: u64,
    pub total_deposited: u64,
    pub timestamp: i64,
}
